application: change-this
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

# Static: Gaebar
- url: /gaebar/static
  static_dir: gaebar/static

- url: /.*
  script: main.py

